// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:2
package tableParser

import __yyfmt__ "fmt"

//line parser.y:2

//line parser.y:6
type yySymType struct {
	yys          int
	stringVal    string
	stringsVal   []string
	boolVal      bool
	column       columnObj
	t_constraint TableConstraint
	t_header     tableHeader
	t_body       tableBody
}

const tokenError = 57346
const tokenEOF = 57347
const tokenUnknown = 57348
const tokenString = 57349
const tokenPgSymbol = 57350
const tokenPgValue = 57351
const tokenLeftParen = 57352
const tokenRightParen = 57353
const tokenComma = 57354
const tokenSemicolon = 57355
const tokenDot = 57356
const tokenKeyword = 57357
const tokenCreate = 57358
const tokenTable = 57359
const tokenIF = 57360
const tokenNOT = 57361
const tokenEXISTS = 57362
const tokenNULL = 57363
const tokenDEFAULT = 57364
const tokenUNIQUE = 57365
const tokenPRIMARY = 57366
const tokenKEY = 57367

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tokenError",
	"tokenEOF",
	"tokenUnknown",
	"tokenString",
	"tokenPgSymbol",
	"tokenPgValue",
	"tokenLeftParen",
	"tokenRightParen",
	"tokenComma",
	"tokenSemicolon",
	"tokenDot",
	"tokenKeyword",
	"tokenCreate",
	"tokenTable",
	"tokenIF",
	"tokenNOT",
	"tokenEXISTS",
	"tokenNULL",
	"tokenDEFAULT",
	"tokenUNIQUE",
	"tokenPRIMARY",
	"tokenKEY",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:240

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 48,
	10, 31,
	14, 31,
	-2, 33,
}

const yyPrivate = 57344

const yyLast = 71

var yyAct = [...]int{

	13, 11, 45, 16, 50, 31, 42, 55, 18, 43,
	40, 34, 22, 32, 14, 15, 33, 30, 34, 44,
	10, 38, 9, 24, 5, 37, 39, 14, 15, 7,
	12, 35, 25, 58, 47, 41, 51, 57, 17, 18,
	26, 28, 54, 27, 47, 63, 56, 52, 53, 19,
	20, 61, 48, 15, 49, 59, 62, 23, 60, 6,
	14, 15, 3, 2, 1, 36, 46, 21, 8, 4,
	29,
}
var yyPact = [...]int{

	8, -1000, -1000, -1000, 49, 12, 7, 20, 38, -1000,
	-1000, 53, 47, -1000, -1000, -1000, -1000, 4, 18, 27,
	7, -6, 17, 53, 1, 53, -1000, -1000, -1000, -13,
	-1000, -1000, -2, 45, -21, 53, 36, -1000, 53, -1000,
	-1000, -1000, -14, 45, -1000, -1000, -1000, 23, -1000, -1000,
	-1000, -1000, -1000, 53, -1000, -1000, -1000, 53, 40, -1000,
	46, -1000, 34, -1000,
}
var yyPgo = [...]int{

	0, 22, 70, 69, 3, 68, 20, 0, 1, 67,
	66, 65, 5, 64, 63, 62, 2,
}
var yyR1 = [...]int{

	0, 13, 14, 15, 3, 3, 4, 4, 5, 5,
	5, 5, 1, 8, 9, 9, 2, 2, 2, 2,
	2, 2, 2, 2, 12, 16, 16, 16, 6, 11,
	11, 7, 7, 10, 10,
}
var yyR2 = [...]int{

	0, 1, 1, 5, 3, 6, 1, 3, 1, 3,
	1, 3, 3, 1, 1, 3, 1, 1, 2, 2,
	2, 2, 3, 3, 2, 1, 5, 3, 4, 1,
	3, 1, 1, 1, 1,
}
var yyChk = [...]int{

	-1000, -13, -14, -15, -3, 16, 10, 17, -5, -1,
	-6, -8, 23, -7, 7, 8, -4, 18, -7, 11,
	12, -9, -7, 10, 19, 14, 13, -1, -6, -2,
	23, -12, 19, 22, 24, 14, -11, -8, 20, -7,
	23, -12, 19, 22, 21, -16, -10, -7, 7, 9,
	25, -7, 11, 12, -4, 21, -16, 14, 10, -8,
	-7, 11, 10, 11,
}
var yyDef = [...]int{

	0, -2, 1, 2, 0, 0, 0, 0, 0, 8,
	10, 0, 0, 13, 31, 32, 4, 0, 6, 0,
	0, 0, 14, 0, 0, 0, 3, 9, 11, 12,
	16, 17, 0, 0, 0, 0, 0, 29, 0, 7,
	20, 21, 0, 0, 18, 19, 25, 0, -2, 34,
	24, 15, 28, 0, 5, 22, 23, 0, 0, 30,
	0, 27, 0, 26,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 3:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:57
		{
			columns := []*TableColumn{}
			constraint := yyDollar[3].t_body.constraint
			for _, obj := range yyDollar[3].t_body.columns {
				columns = append(columns, obj.Column())
				if obj.PrimaryKey {
					constraint.PrimaryKey = append(constraint.PrimaryKey, obj.Name)
				}
				if obj.Unique {
					constraint.Uniques = append(constraint.Uniques, []string{obj.Name})
				}
			}
			ast := yylex.(*lexer).ast
			ast.Schema = yyDollar[1].t_header.Schema
			ast.Table = yyDollar[1].t_header.Table
			ast.Columns = columns
			ast.Constraint = &constraint
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:77
		{
			yyVAL.t_header = yyDollar[3].t_header
		}
	case 5:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:81
		{
			yyVAL.t_header = yyDollar[6].t_header
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:87
		{
			yyVAL.t_header.Table = yyDollar[1].stringVal
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:91
		{
			yyVAL.t_header.Schema = yyDollar[1].stringVal
			yyVAL.t_header.Table = yyDollar[3].stringVal
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:98
		{
			yyVAL.t_body.columns = []columnObj{yyDollar[1].column}
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:102
		{
			yyVAL.t_body.columns = append(yyVAL.t_body.columns, yyDollar[3].column)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:106
		{
			yyVAL.t_body.constraint = yyDollar[1].t_constraint
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:110
		{
			yyVAL.t_body.constraint = combineConstraint(yyVAL.t_body.constraint, yyDollar[3].t_constraint)
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:165
		{
			yyVAL.column = yyDollar[3].column
			yyVAL.column.Name = yyDollar[1].stringVal
			yyVAL.column.Type = yyDollar[2].stringVal
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:176
		{
			yyVAL.stringVal = __yyfmt__.Sprintf("%s.%s", yyDollar[1].stringVal, yyDollar[3].stringVal)
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:182
		{
			yyVAL.column.Unique = true
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:186
		{
			yyVAL.column.PrimaryKey = true
		}
	case 18:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:190
		{
			yyVAL.column.NotNull = true
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:194
		{
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:197
		{
			yyVAL.column.PrimaryKey = true
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:201
		{
			yyVAL.column.PrimaryKey = true
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:205
		{
			yyVAL.column.NotNull = true
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:211
		{
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:220
		{
			yyVAL.t_constraint.Uniques = append(yyVAL.t_constraint.Uniques, yyDollar[3].stringsVal)
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:226
		{
			yyVAL.stringsVal = []string{yyDollar[1].stringVal}
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:230
		{
			yyVAL.stringsVal = append(yyDollar[1].stringsVal, yyDollar[3].stringVal)
		}
	}
	goto yystack /* stack new state and value */
}
