// Code generated by goyacc -o parser.go parser.y. DO NOT EDIT.

//line parser.y:2
package tableParser

import __yyfmt__ "fmt"

//line parser.y:2

//line parser.y:5
type yySymType struct {
	yys     int
	val     string
	column  *TableColumn
	columns []*TableColumn
}

const tokenError = 57346
const tokenEOF = 57347
const tokenUnknown = 57348
const tokenString = 57349
const tokenPgSymbol = 57350
const tokenPgValue = 57351
const tokenLeftParen = 57352
const tokenRightParen = 57353
const tokenComma = 57354
const tokenSemicolon = 57355
const tokenDot = 57356
const tokenKeyword = 57357
const tokenCreate = 57358
const tokenTable = 57359
const tokenIF = 57360
const tokenNOT = 57361
const tokenEXISTS = 57362
const tokenNULL = 57363
const tokenDEFAULT = 57364
const tokenUNIQUE = 57365

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tokenError",
	"tokenEOF",
	"tokenUnknown",
	"tokenString",
	"tokenPgSymbol",
	"tokenPgValue",
	"tokenLeftParen",
	"tokenRightParen",
	"tokenComma",
	"tokenSemicolon",
	"tokenDot",
	"tokenKeyword",
	"tokenCreate",
	"tokenTable",
	"tokenIF",
	"tokenNOT",
	"tokenEXISTS",
	"tokenNULL",
	"tokenDEFAULT",
	"tokenUNIQUE",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line parser.y:141

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 56,
	10, 32,
	14, 32,
	-2, 34,
}

const yyPrivate = 57344

const yyLast = 76

var yyAct = [...]int{

	20, 18, 53, 11, 61, 49, 8, 6, 9, 10,
	52, 39, 21, 13, 5, 22, 4, 50, 17, 29,
	51, 48, 8, 40, 19, 42, 41, 38, 16, 31,
	9, 10, 44, 14, 24, 45, 64, 47, 59, 60,
	63, 7, 55, 58, 23, 46, 36, 34, 35, 32,
	33, 27, 55, 69, 62, 25, 26, 67, 56, 10,
	57, 43, 65, 68, 66, 12, 30, 9, 10, 37,
	3, 2, 1, 54, 28, 15,
}
var yyPact = [...]int{

	0, -1000, -1000, -1000, -3, 23, 55, -6, 19, -1000,
	-1000, -1000, 1, -8, 60, 1, 44, 39, 60, 56,
	-1000, 60, -1000, 38, 36, 33, -1000, -1000, 4, 11,
	60, 55, 32, -1000, 24, -1000, -1000, -2, -1000, -1000,
	-11, 51, 60, 27, -1000, -1000, -1000, -1000, -1000, -1000,
	-17, 51, -1000, -1000, -1000, 26, -1000, -1000, -1000, -1000,
	60, -1000, -1000, 60, 46, -1000, 53, -1000, 42, -1000,
}
var yyPgo = [...]int{

	0, 28, 75, 0, 1, 74, 73, 72, 71, 70,
	7, 3, 18, 69, 2, 61,
}
var yyR1 = [...]int{

	0, 7, 8, 9, 9, 10, 10, 11, 11, 11,
	2, 2, 2, 2, 1, 4, 5, 5, 13, 13,
	13, 13, 13, 13, 13, 13, 14, 14, 14, 12,
	15, 15, 3, 3, 6, 6,
}
var yyR2 = [...]int{

	0, 1, 1, 4, 7, 1, 3, 5, 5, 4,
	2, 2, 3, 3, 3, 1, 1, 3, 1, 1,
	2, 2, 2, 2, 3, 3, 1, 5, 3, 4,
	1, 3, 1, 1, 1, 1,
}
var yyChk = [...]int{

	-1000, -7, -8, -9, 16, 17, -10, 18, -3, 7,
	8, -11, 10, 19, 14, -2, -1, -12, -4, 23,
	-3, 20, -3, -1, -12, 11, 12, 12, -5, -3,
	10, -10, 11, 12, 11, 12, 13, -13, 23, 7,
	19, 22, 14, -15, -4, -11, 13, 13, 23, 7,
	19, 22, 21, -14, -6, -3, 7, 9, -3, 11,
	12, 21, -14, 14, 10, -4, -3, 11, 10, 11,
}
var yyDef = [...]int{

	0, -2, 1, 2, 0, 0, 0, 0, 5, 32,
	33, 3, 0, 0, 0, 0, 0, 0, 0, 0,
	15, 0, 6, 0, 0, 0, 10, 11, 0, 16,
	0, 0, 0, 12, 0, 13, 9, 14, 18, 19,
	0, 0, 0, 0, 30, 4, 7, 8, 22, 23,
	0, 0, 20, 21, 26, 0, -2, 35, 17, 29,
	0, 24, 25, 0, 0, 31, 0, 28, 0, 27,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:50
		{
			yylex.(*lexer).ast.Table = yyDollar[1].val
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:54
		{
			yylex.(*lexer).ast.Schema = yyDollar[1].val
			yylex.(*lexer).ast.Table = yyDollar[3].val
		}
	case 7:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:62
		{
			ast := yylex.(*lexer).ast
			ast.Columns = append(yyDollar[2].columns, yyDollar[3].column)
		}
	case 8:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:67
		{
			ast := yylex.(*lexer).ast
			ast.Columns = yyDollar[2].columns
		}
	case 9:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:72
		{
			ast := yylex.(*lexer).ast
			ast.Columns = []*TableColumn{
				yyDollar[2].column,
			}
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:81
		{
			yyVAL.columns = []*TableColumn{
				yyDollar[1].column,
			}
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:87
		{
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:90
		{
			yyVAL.columns = append(yyDollar[1].columns, yyDollar[2].column)
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:97
		{
			yyVAL.column = &TableColumn{
				Name: yyDollar[1].val,
				Type: yyDollar[2].val,
			}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:109
		{
			yyVAL.val = __yyfmt__.Sprintf("%s.%s", yyDollar[1].val, yyDollar[3].val)
		}
	}
	goto yystack /* stack new state and value */
}
